#!/usr/bin/env python3
"""
Convert raw/ugly math expressions into visually readable, properly formatted LaTeX
for Obsidian and GitHub markdown.
"""
import os, re, sys

FOLDERS = [
    r"C:\Obsidian\Brain Original\AIGIS",
    r"/tmp/github_repo",
]

def fix_math(text):
    """Fix math expression formatting for visual readability."""
    
    # Fix common double-backslash LaTeX commands inside math mode
    # Pattern: match math content and fix backslashes within it
    def fix_inline_math(match):
        content = match.group(1)
        # Fix double backslashes for common LaTeX commands
        content = content.replace('\\\\frac', '\\frac')
        content = content.replace('\\\\sum', '\\sum')
        content = content.replace('\\\\sqrt', '\\sqrt')
        content = content.replace('\\\\cdot', '\\cdot')
        content = content.replace('\\\\text', '\\text')
        content = content.replace('\\\\begin', '\\begin')
        content = content.replace('\\\\end', '\\end')
        content = content.replace('\\\\left', '\\left')
        content = content.replace('\\\\right', '\\right')
        content = content.replace('\\\\times', '\\times')
        content = content.replace('\\\\mathbb', '\\mathbb')
        content = content.replace('\\\\mathbf', '\\mathbf')
        content = content.replace('\\\\boldsymbol', '\\boldsymbol')
        content = content.replace('\\\\alpha', '\\alpha')
        content = content.replace('\\\\beta', '\\beta')
        content = content.replace('\\\\gamma', '\\gamma')
        content = content.replace('\\\\delta', '\\delta')
        content = content.replace('\\\\epsilon', '\\epsilon')
        content = content.replace('\\\\varepsilon', '\\varepsilon')
        content = content.replace('\\\\zeta', '\\zeta')
        content = content.replace('\\\\eta', '\\eta')
        content = content.replace('\\\\theta', '\\theta')
        content = content.replace('\\\\iota', '\\iota')
        content = content.replace('\\\\kappa', '\\kappa')
        content = content.replace('\\\\lambda', '\\lambda')
        content = content.replace('\\\\mu', '\\mu')
        content = content.replace('\\\\nu', '\\nu')
        content = content.replace('\\\\xi', '\\xi')
        content = content.replace('\\\\pi', '\\pi')
        content = content.replace('\\\\rho', '\\rho')
        content = content.replace('\\\\sigma', '\\sigma')
        content = content.replace('\\\\tau', '\\tau')
        content = content.replace('\\\\phi', '\\phi')
        content = content.replace('\\\\varphi', '\\varphi')
        content = content.replace('\\\\chi', '\\chi')
        content = content.replace('\\\\psi', '\\psi')
        content = content.replace('\\\\omega', '\\omega')
        content = content.replace('\\\\Gamma', '\\Gamma')
        content = content.replace('\\\\Delta', '\\Delta')
        content = content.replace('\\\\Theta', '\\Theta')
        content = content.replace('\\\\Lambda', '\\Lambda')
        content = content.replace('\\\\Sigma', '\\Sigma')
        content = content.replace('\\\\Phi', '\\Phi')
        content = content.replace('\\\\Psi', '\\Psi')
        content = content.replace('\\\\Omega', '\\Omega')
        content = content.replace('\\\\leq', '\\leq')
        content = content.replace('\\\\geq', '\\geq')
        content = content.replace('\\\\neq', '\\neq')
        content = content.replace('\\\\approx', '\\approx')
        content = content.replace('\\\\equiv', '\\equiv')
        content = content.replace('\\\\sim', '\\sim')
        content = content.replace('\\\\propto', '\\propto')
        content = content.replace('\\\\infty', '\\infty')
        content = content.replace('\\\\partial', '\\partial')
        content = content.replace('\\\\nabla', '\\nabla')
        content = content.replace('\\\\angle', '\\angle')
        content = content.replace('\\\\circ', '\\circ')
        content = content.replace('\\\\degree', '\\degree')
        content = content.replace('\\\\prime', '\\prime')
        content = content.replace('\\\\hat', '\\hat')
        content = content.replace('\\\\bar', '\\bar')
        content = content.replace('\\\\tilde', '\\tilde')
        content = content.replace('\\\\vec', '\\vec')
        content = content.replace('\\\\overline', '\\overline')
        content = content.replace('\\\\underline', '\\underline')
        content = content.replace('\\\\int', '\\int')
        content = content.replace('\\\\iint', '\\iint')
        content = content.replace('\\\\iiint', '\\iiint')
        content = content.replace('\\\\oint', '\\oint')
        content = content.replace('\\\\prod', '\\prod')
        content = content.replace('\\\\coprod', '\\coprod')
        content = content.replace('\\\\bigcup', '\\bigcup')
        content = content.replace('\\\\bigcap', '\\bigcap')
        content = content.replace('\\\\bigoplus', '\\bigoplus')
        content = content.replace('\\\\bigotimes', '\\bigotimes')
        content = content.replace('\\\\lim', '\\lim')
        content = content.replace('\\\\max', '\\max')
        content = content.replace('\\\\min', '\\min')
        content = content.replace('\\\\sup', '\\sup')
        content = content.replace('\\\\inf', '\\inf')
        content = content.replace('\\\\arg', '\\arg')
        content = content.replace('\\\\sin', '\\sin')
        content = content.replace('\\\\cos', '\\cos')
        content = content.replace('\\\\tan', '\\tan')
        content = content.replace('\\\\sec', '\\sec')
        content = content.replace('\\\\csc', '\\csc')
        content = content.replace('\\\\cot', '\\cot')
        content = content.replace('\\\\log', '\\log')
        content = content.replace('\\\\ln', '\\ln')
        content = content.replace('\\\\exp', '\\exp')
        content = content.replace('\\\\det', '\\det')
        content = content.replace('\\\\dim', '\\dim')
        content = content.replace('\\\\ker', '\\ker')
        content = content.replace('\\\\hom', '\\hom')
        content = content.replace('\\\\deg', '\\deg')
        content = content.replace('\\\\gcd', '\\gcd')
        content = content.replace('\\\\Pr', '\\Pr')
        content = content.replace('\\\\bmod', '\\bmod')
        content = content.replace('\\\\pmod', '\\pmod')
        content = content.replace('\\\\dbinom', '\\dbinom')
        content = content.replace('\\\\binom', '\\binom')
        content = content.replace('\\\\tbinom', '\\tbinom')
        content = content.replace('\\\\choose', '\\choose')
        content = content.replace('\\\\sqrt', '\\sqrt')
        content = content.replace('\\\\cbrt', '\\cbrt')
        content = content.replace('\\\\dfrac', '\\dfrac')
        content = content.replace('\\\\tfrac', '\\tfrac')
        content = content.replace('\\\\cfrac', '\\cfrac')
        content = content.replace('\\\\cancel', '\\cancel')
        content = content.replace('\\\\bcancel', '\\bcancel')
        content = content.replace('\\\\xcancel', '\\xcancel')
        content = content.replace('\\\\sout', '\\sout')
        content = content.replace('\\\\rlap', '\\rlap')
        content = content.replace('\\\\llap', '\\llap')
        content = content.replace('\\\\smash', '\\smash')
        content = content.replace('\\\\phantom', '\\phantom')
        content = content.replace('\\\\hphantom', '\\hphantom')
        content = content.replace('\\\\vphantom', '\\vphantom')
        content = content.replace('\\\\mathstrut', '\\mathstrut')
        
        # Also fix escaped brackets
        content = content.replace('\\\\[', '[')
        content = content.replace('\\\\]', ']')
        
        # Remove extra spaces inside math delimiters
        content = content.strip()
        return '$' + content + '$'
    
    def fix_display_math(match):
        content = match.group(1)
        # Same fixes as inline
        content = content.replace('\\\\frac', '\\frac')
        content = content.replace('\\\\sum', '\\sum')
        content = content.replace('\\\\sqrt', '\\sqrt')
        content = content.replace('\\\\cdot', '\\cdot')
        content = content.replace('\\\\text', '\\text')
        content = content.replace('\\\\begin', '\\begin')
        content = content.replace('\\\\end', '\\end')
        content = content.replace('\\\\left', '\\left')
        content = content.replace('\\\\right', '\\right')
        content = content.replace('\\\\times', '\\times')
        content = content.replace('\\\\mathbb', '\\mathbb')
        content = content.replace('\\\\mathbf', '\\mathbf')
        content = content.replace('\\\\boldsymbol', '\\boldsymbol')
        content = content.replace('\\\\alpha', '\\alpha')
        content = content.replace('\\\\beta', '\\beta')
        content = content.replace('\\\\gamma', '\\gamma')
        content = content.replace('\\\\delta', '\\delta')
        content = content.replace('\\\\epsilon', '\\epsilon')
        content = content.replace('\\\\varepsilon', '\\varepsilon')
        content = content.replace('\\\\zeta', '\\zeta')
        content = content.replace('\\\\eta', '\\eta')
        content = content.replace('\\\\theta', '\\theta')
        content = content.replace('\\\\iota', '\\iota')
        content = content.replace('\\\\kappa', '\\kappa')
        content = content.replace('\\\\lambda', '\\lambda')
        content = content.replace('\\\\mu', '\\mu')
        content = content.replace('\\\\nu', '\\nu')
        content = content.replace('\\\\xi', '\\xi')
        content = content.replace('\\\\pi', '\\pi')
        content = content.replace('\\\\rho', '\\rho')
        content = content.replace('\\\\sigma', '\\sigma')
        content = content.replace('\\\\tau', '\\tau')
        content = content.replace('\\\\phi', '\\phi')
        content = content.replace('\\\\varphi', '\\varphi')
        content = content.replace('\\\\chi', '\\chi')
        content = content.replace('\\\\psi', '\\psi')
        content = content.replace('\\\\omega', '\\omega')
        content = content.replace('\\\\Gamma', '\\Gamma')
        content = content.replace('\\\\Delta', '\\Delta')
        content = content.replace('\\\\Theta', '\\Theta')
        content = content.replace('\\\\Lambda', '\\Lambda')
        content = content.replace('\\\\Sigma', '\\Sigma')
        content = content.replace('\\\\Phi', '\\Phi')
        content = content.replace('\\\\Psi', '\\Psi')
        content = content.replace('\\\\Omega', '\\Omega')
        content = content.replace('\\\\leq', '\\leq')
        content = content.replace('\\\\geq', '\\geq')
        content = content.replace('\\\\neq', '\\neq')
        content = content.replace('\\\\approx', '\\approx')
        content = content.replace('\\\\equiv', '\\equiv')
        content = content.replace('\\\\sim', '\\sim')
        content = content.replace('\\\\propto', '\\propto')
        content = content.replace('\\\\infty', '\\infty')
        content = content.replace('\\\\partial', '\\partial')
        content = content.replace('\\\\nabla', '\\nabla')
        content = content.replace('\\\\angle', '\\angle')
        content = content.replace('\\\\circ', '\\circ')
        content = content.replace('\\\\degree', '\\degree')
        content = content.replace('\\\\prime', '\\prime')
        content = content.replace('\\\\hat', '\\hat')
        content = content.replace('\\\\bar', '\\bar')
        content = content.replace('\\\\tilde', '\\tilde')
        content = content.replace('\\\\vec', '\\vec')
        content = content.replace('\\\\overline', '\\overline')
        content = content.replace('\\\\underline', '\\underline')
        content = content.replace('\\\\int', '\\int')
        content = content.replace('\\\\iint', '\\iint')
        content = content.replace('\\\\iiint', '\\iiint')
        content = content.replace('\\\\oint', '\\oint')
        content = content.replace('\\\\prod', '\\prod')
        content = content.replace('\\\\coprod', '\\coprod')
        content = content.replace('\\\\bigcup', '\\bigcup')
        content = content.replace('\\\\bigcap', '\\bigcap')
        content = content.replace('\\\\bigoplus', '\\bigoplus')
        content = content.replace('\\\\bigotimes', '\\bigotimes')
        content = content.replace('\\\\lim', '\\lim')
        content = content.replace('\\\\max', '\\max')
        content = content.replace('\\\\min', '\\min')
        content = content.replace('\\\\sup', '\\sup')
        content = content.replace('\\\\inf', '\\inf')
        content = content.replace('\\\\arg', '\\arg')
        content = content.replace('\\\\sin', '\\sin')
        content = content.replace('\\\\cos', '\\cos')
        content = content.replace('\\\\tan', '\\tan')
        content = content.replace('\\\\sec', '\\sec')
        content = content.replace('\\\\csc', '\\csc')
        content = content.replace('\\\\cot', '\\cot')
        content = content.replace('\\\\log', '\\log')
        content = content.replace('\\\\ln', '\\ln')
        content = content.replace('\\\\exp', '\\exp')
        content = content.replace('\\\\det', '\\det')
        content = content.replace('\\\\dim', '\\dim')
        content = content.replace('\\\\ker', '\\ker')
        content = content.replace('\\\\hom', '\\hom')
        content = content.replace('\\\\deg', '\\deg')
        content = content.replace('\\\\gcd', '\\gcd')
        content = content.replace('\\\\Pr', '\\Pr')
        content = content.replace('\\\\bmod', '\\bmod')
        content = content.replace('\\\\pmod', '\\pmod')
        content = content.replace('\\\\dbinom', '\\dbinom')
        content = content.replace('\\\\binom', '\\binom')
        content = content.replace('\\\\tbinom', '\\tbinom')
        content = content.replace('\\\\choose', '\\choose')
        content = content.replace('\\\\sqrt', '\\sqrt')
        content = content.replace('\\\\cbrt', '\\cbrt')
        content = content.replace('\\\\dfrac', '\\dfrac')
        content = content.replace('\\\\tfrac', '\\tfrac')
        content = content.replace('\\\\cfrac', '\\cfrac')
        content = content.replace('\\\\cancel', '\\cancel')
        content = content.replace('\\\\bcancel', '\\bcancel')
        content = content.replace('\\\\xcancel', '\\xcancel')
        content = content.replace('\\\\sout', '\\sout')
        content = content.replace('\\\\rlap', '\\rlap')
        content = content.replace('\\\\llap', '\\llap')
        content = content.replace('\\\\smash', '\\smash')
        content = content.replace('\\\\phantom', '\\phantom')
        content = content.replace('\\\\hphantom', '\\hphantom')
        content = content.replace('\\\\vphantom', '\\vphantom')
        content = content.replace('\\\\mathstrut', '\\mathstrut')
        
        # Also fix escaped brackets
        content = content.replace('\\\\[', '[')
        content = content.replace('\\\\]', ']')
        
        content = content.strip()
        return '$$' + content + '$$'
    
    # Fix inline math $...$
    text = re.sub(r'\$([^$\n]+?)\$', fix_inline_math, text)
    
    # Fix display math $$...$$
    text = re.sub(r'\$\$([\s\S]+?)\$\$', fix_display_math, text)
    
    # Fix display math spacing - ensure $$ has empty lines around it
    text = re.sub(r'([^\n])\n(\$\$)', r'\1\n\n\2', text)
    text = re.sub(r'(\$\$)\n([^\n$])', r'\1\n\n\2', text)
    
    return text

def process_folder(folder):
    if not os.path.exists(folder):
        print(f"Folder not found: {folder}")
        return 0
    
    count = 0
    for root, dirs, fnames in os.walk(folder):
        if '.git' in root or '_Inbox' in root or '_processed' in root:
            continue
        for fn in fnames:
            if not fn.endswith('.md'):
                continue
            path = os.path.join(root, fn)
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    original = f.read()
                updated = fix_math(original)
                if updated != original:
                    with open(path, 'w', encoding='utf-8') as f:
                        f.write(updated)
                    count += 1
            except Exception as e:
                print(f"Error on {path}: {e}")
    return count

if __name__ == '__main__':
    total = 0
    for folder in FOLDERS:
        print(f"Processing: {folder}")
        n = process_folder(folder)
        print(f"  Files fixed: {n}")
        total += n
    print(f"\nTotal files fixed across all folders: {total}")